name: buildroot

on:
  push:
#    branches:
#      - main
    tags:
      - v*
      
  workflow_dispatch:
    inputs:
      git-address:
        description: 'git-address'
        required: true
        default: 'https://github.com/buildroot/buildroot.git'
      branches-tags:
        description: 'branches-tags'
        required: true
        default: '2023.02.x'
      board:
        description: 'board'
        required: true
        default: 'tcrpfriend'
jobs:
  build:
    runs-on: ubuntu-latest  # 또는 원하는 운영 체제 버전 지정
    steps:
      - uses: actions/checkout@v2
      - name: Clone source code
        run: |
          git clone ${{github.event.inputs.git-address}} /opt/buildroot
          cd /opt/buildroot
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev
          
      - name: Bring over config files from redpill-load
        run: |
          mkdir /opt/config-files
          cd /opt/config-files
          git clone https://github.com/PeterSuh-Q3/redpill-load.git
          ls -ltr /opt/config-files/redpill-load/config 
      - name: Build
        run: |
          mkdir /opt/firmware
          cd /opt/buildroot
          git checkout ${{github.event.inputs.branches-tags}}
          git pull origin ${{github.event.inputs.branches-tags}}
          cp -rf /home/runner/work/tcrpfriend/tcrpfriend/buildroot/* .
          cp -rf /opt/config-files/redpill-load/config /home/runner/work/tcrpfriend/tcrpfriend/buildroot/board/tcrpfriend/rootfs-overlay/root/
          chmod 777 board/tcrpfriend/rootfs-overlay/root/*.sh
          chmod 777 board/tcrpfriend/rootfs-overlay/root/tools/*
          VERSION=`grep "BOOTVER=" /home/runner/work/tcrpfriend/tcrpfriend/buildroot/board/tcrpfriend/rootfs-overlay/root/boot.sh | awk -F\" '{print $2}'`
          echo "Version: ${VERSION}"
          echo '---start make---'
          make ${{github.event.inputs.board}}_defconfig
          make

          KERNEL_VERSION="$(grep BR2_LINUX_KERNEL_VERSION ${{github.event.inputs.board}}_defconfig | cut -d'=' -f2 | tr -d '"')"
          echo "KERNEL_VERSION=${KERNEL_VERSION}" >> $GITHUB_ENV
          
          cp -r /opt/buildroot/output/images /opt/firmware
      - name: Upload buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
        uses: actions/upload-artifact@v3
        with:
          name: buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
          path: /opt/firmware
